# Generated by Django 4.0 on 2023-08-28 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='USER_ID',
        ),
    ]
