# Generated by Django 4.0 on 2023-08-28 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookie', '0002_remove_pet_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('USER_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cookie.accounts')),
                ('PET_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cookie.pet')),
            ],
        ),
    ]
